// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvGKyHq6y2stBx1Qc3yaKCqaIgwehcW48',
    appId: '1:1088345598382:web:9f43ea4a9fcf07ddd5803f',
    messagingSenderId: '1088345598382',
    projectId: 'consultone-7e371',
    authDomain: 'consultone-7e371.firebaseapp.com',
    storageBucket: 'consultone-7e371.firebasestorage.app',
    measurementId: 'G-YF82D11K0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZcfoRgLSLFXo34rvHXVyE7A0vOkhO2wk',
    appId: '1:1088345598382:android:a7c6d68d6c1ce9a3d5803f',
    messagingSenderId: '1088345598382',
    projectId: 'consultone-7e371',
    storageBucket: 'consultone-7e371.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3x1ieexX_CiSoMYdu3vF94BKts2pSW9A',
    appId: '1:1088345598382:ios:061bfabeb8b923d5d5803f',
    messagingSenderId: '1088345598382',
    projectId: 'consultone-7e371',
    storageBucket: 'consultone-7e371.firebasestorage.app',
    iosBundleId: 'com.example.medappFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3x1ieexX_CiSoMYdu3vF94BKts2pSW9A',
    appId: '1:1088345598382:ios:061bfabeb8b923d5d5803f',
    messagingSenderId: '1088345598382',
    projectId: 'consultone-7e371',
    storageBucket: 'consultone-7e371.firebasestorage.app',
    iosBundleId: 'com.example.medappFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvGKyHq6y2stBx1Qc3yaKCqaIgwehcW48',
    appId: '1:1088345598382:web:ec0a64939f7e30dcd5803f',
    messagingSenderId: '1088345598382',
    projectId: 'consultone-7e371',
    authDomain: 'consultone-7e371.firebaseapp.com',
    storageBucket: 'consultone-7e371.firebasestorage.app',
    measurementId: 'G-VTF8RH9LGS',
  );
}
